version: '3.2'
    
services:
  db:
    image: django/mysql:1.8b
    build: ./db
    container_name: 'django_db_my8_b'
    ports: 
      - 3306:3306
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kintai_db
      - MYSQL_USER=my
      - MYSQL_PASSWORD=my
    volumes:
      - ../db/database:/var/lib/mysql
      - ../db/init:/docker-entrypoint-initdb.d  
    command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx
  app:
    image: django/web:1.8b
    build: ./app
    container_name: 'django_app_my8_b'
    expose:
      - "8001"
    ports:
      - 3000:3000
    environment:
      - DEBUG=1
    depends_on:
      - db
    stdin_open: true
    tty: true
    volumes:
      - ../app:/home/user1/dev
      - ../app/log:/app/log
      - ../app/static:/home/user1/dev/static
    working_dir:
      /home/user1/dev      
    command: uwsgi --socket :8001 --module myprj.wsgi --py-autoreload 1 --logto /app/log/uwsgi.log
  web:
    image: nginx:1.19
    container_name: 'django_web_my8_b'
    ports:
      - '8080:80'
    depends_on:
      - app
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ../web/log:/var/log/nginx
      - ../app:/home/user1/dev
      - ../app/static:/static
