version: '3.2'
    
services:
  gitLab:
    image: gitlab/gitlab-ce:latest
    ports:
     - "80:80"
     - "4022:22"
     
    volumes:
     - './config:/etc/gitlab'
     - './logs:/var/log/gitlab'
     - './data:/var/opt/gitlab'