version: '3'
    
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssqlserver01
    ports:
     - 1433:1433
    environment: 
     - ACCEPT_EULA=Y
     - SA_PASSWORD=pAss@123
     - MSSQL_PID=Express
     - MSSQL_LCID=1041
     - MSSQL_COLLATION=Japanese_CI_AS
    volumes:
     - './data:/var/opt/mssql/data'
     - './log:/var/opt/mssql/log'
     - './secrets:/var/opt/mssql/secrets'